import type { MealSlot, Recipe } from "@/types/domain";

export const seedRecipes: Recipe[] = [
  {
    id: "r1",
    name: "Poha",
    mealSlot: "breakfast",
    cuisine: "Maharashtrian",
    dietMode: "veg",
    spiceLevel: "low",
    prepTimeMins: 8,
    cookTimeMins: 12,
    ingredients: [
      { name: "Flattened rice", quantity: "2 cups" },
      { name: "Onion", quantity: "1 medium" },
      { name: "Peanuts", quantity: "2 tbsp" },
    ],
    steps: ["Rinse poha lightly.", "Saute onion and peanuts.", "Mix poha and steam 2 mins."],
    popularityScore: 85,
  },
  {
    id: "r2",
    name: "Masala Omelette",
    mealSlot: "breakfast",
    cuisine: "Indian",
    dietMode: "non_veg",
    spiceLevel: "medium",
    prepTimeMins: 5,
    cookTimeMins: 10,
    ingredients: [
      { name: "Eggs", quantity: "3" },
      { name: "Onion", quantity: "1 small" },
      { name: "Tomato", quantity: "1 small" },
    ],
    steps: ["Beat eggs with vegetables.", "Cook on pan till set.", "Serve hot."],
    popularityScore: 78,
  },
  {
    id: "r3",
    name: "Rajma Chawal",
    mealSlot: "lunch",
    cuisine: "North Indian",
    dietMode: "veg",
    spiceLevel: "medium",
    prepTimeMins: 15,
    cookTimeMins: 30,
    ingredients: [
      { name: "Rajma", quantity: "1 cup" },
      { name: "Rice", quantity: "1.5 cups" },
      { name: "Tomato puree", quantity: "1 cup" },
    ],
    steps: ["Pressure cook rajma.", "Cook masala gravy.", "Simmer and serve with rice."],
    popularityScore: 89,
  },
  {
    id: "r4",
    name: "Chicken Curry",
    mealSlot: "lunch",
    cuisine: "Indian",
    dietMode: "non_veg",
    spiceLevel: "high",
    prepTimeMins: 20,
    cookTimeMins: 35,
    ingredients: [
      { name: "Chicken", quantity: "500g" },
      { name: "Onion", quantity: "2 medium" },
      { name: "Ginger garlic paste", quantity: "1 tbsp" },
    ],
    steps: ["Brown onions.", "Add chicken and spices.", "Cook till tender."],
    popularityScore: 82,
  },
  {
    id: "r5",
    name: "Paneer Bhurji",
    mealSlot: "dinner",
    cuisine: "North Indian",
    dietMode: "veg",
    spiceLevel: "medium",
    prepTimeMins: 10,
    cookTimeMins: 15,
    ingredients: [
      { name: "Paneer", quantity: "250g" },
      { name: "Capsicum", quantity: "1 small" },
      { name: "Tomato", quantity: "1 medium" },
    ],
    steps: ["Saute veggies.", "Add spices and paneer.", "Cook for 5 mins."],
    popularityScore: 87,
  },
  {
    id: "r6",
    name: "Egg Curry",
    mealSlot: "dinner",
    cuisine: "Indian",
    dietMode: "non_veg",
    spiceLevel: "medium",
    prepTimeMins: 12,
    cookTimeMins: 20,
    ingredients: [
      { name: "Boiled eggs", quantity: "4" },
      { name: "Onion", quantity: "1 medium" },
      { name: "Tomato", quantity: "1 medium" },
    ],
    steps: ["Cook masala base.", "Add eggs and gravy.", "Simmer and serve."],
    popularityScore: 80,
  },
  {
    id: "r7",
    name: "Sprouts Chaat",
    mealSlot: "snack",
    cuisine: "Indian",
    dietMode: "veg",
    spiceLevel: "low",
    prepTimeMins: 8,
    cookTimeMins: 5,
    ingredients: [
      { name: "Sprouts", quantity: "1 cup" },
      { name: "Onion", quantity: "1 small" },
      { name: "Lemon", quantity: "1/2" },
    ],
    steps: ["Mix all ingredients.", "Season lightly.", "Serve fresh."],
    popularityScore: 74,
  },
  {
    id: "r8",
    name: "Chicken Sandwich",
    mealSlot: "snack",
    cuisine: "Continental",
    dietMode: "non_veg",
    spiceLevel: "low",
    prepTimeMins: 10,
    cookTimeMins: 8,
    ingredients: [
      { name: "Bread", quantity: "4 slices" },
      { name: "Cooked chicken", quantity: "150g" },
      { name: "Mayo", quantity: "2 tbsp" },
    ],
    steps: ["Mix filling.", "Toast sandwich.", "Cut and serve."],
    popularityScore: 72,
  },
];

export function recipesBySlot(slot: MealSlot) {
  return seedRecipes.filter((recipe) => recipe.mealSlot === slot);
}
